package cp.companion;

import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;



public class InfoDialog extends javax.swing.JFrame {

    private static InfoDialog infoWin;    
    
    /**
     * Creates new form VentanitaInf
     */
    public InfoDialog() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(InfoDialog.DISPOSE_ON_CLOSE);
        
        labelImage.setText("");
        
    }
    

    public static InfoDialog GetInstance() throws ClassNotFoundException {
        if (infoWin == null) {
            infoWin = new InfoDialog();
        }
       
        return infoWin;
    }

        
    public void setLabelImage (boolean success)
    {
        String path;
        if (success){path = "resources/success.png";}
        else {path = "resources/alert.png";}
        
        URL url = this.getClass().getResource(path);  
        ImageIcon icon = new ImageIcon(url);  
        Image img = icon.getImage();
        Image img2 = img.getScaledInstance(27, 27,  java.awt.Image.SCALE_SMOOTH);
        ImageIcon icon2 = new ImageIcon(img2);
        labelImage.setIcon(icon2);
    }
        
        
    public void setLabelText (String text)
    {
        labelInfo.setText(text);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelInfo = new javax.swing.JLabel();
        btnAceptar1 = new javax.swing.JButton();
        labelImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aviso");
        setResizable(false);

        labelInfo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelInfo.setText("Clase agregada con éxito!");

        btnAceptar1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAceptar1.setText("Aceptar");
        btnAceptar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar1ActionPerformed(evt);
            }
        });

        labelImage.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(labelImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelInfo)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(btnAceptar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInfo)
                    .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnAceptar1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAceptar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar1;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelInfo;
    // End of variables declaration//GEN-END:variables
}
